In [ ]:
#Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

#Q1

In [ ]:
import numpy as np

# 1. Create random vector
random_vector = np.random.randint(1, 21, 15)
print("Original vector:", random_vector)

# 2. Reshape the array
reshaped_array = random_vector.reshape(3, 5)
print("\nReshaped array:\n", reshaped_array)

# 3. Print array shape
print("\nArray shape:", reshaped_array.shape)

# 4. Replace the max in each row by 0
for row in reshaped_array:
    row[row.argmax()] = 0
print("\nArray after replacing with 0:\n", reshaped_array)

Original vector: [16  8 14 18 15 12  5  4 18 19  3  2 18  7  7]

Reshaped array:
 [[16  8 14 18 15]
 [12  5  4 18 19]
 [ 3  2 18  7  7]]

Array shape: (3, 5)

Array after replacing with 0:
 [[16  8 14  0 15]
 [12  5  4 18  0]
 [ 3  2  0  7  7]]


#Q2

In [ ]:
import numpy as np

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)

# Print the array
print("Array:\n", array_2d)

# Print the shape of the array
print("\nShape of the array:", array_2d.shape)

# Print the type of the array
print("\nType of the array:", type(array_2d))

# Print the data type of the array's elements
print("\nData type of the array's elements:", array_2d.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of the array: (4, 3)

Type of the array: <class 'numpy.ndarray'>

Data type of the array's elements: int32


#Q3

In [ ]:
def diagonal_sum(matrix):
    # Use min to ensure we don't exceed the index for non-square matrices
    return sum(matrix[i][i] for i in range(min(len(matrix), len(matrix[0]))))

matrix = [[0, 1, 2],
          [3, 4, 5]]

print(diagonal_sum(matrix))


4


#Q4

In [ ]:
import numpy as np

# a. Create an array of odd and even numbers between 10 to 70:

# Create an array of odd numbers
odd_numbers = np.arange(11, 70, 2)
print("Odd numbers:", odd_numbers)

# Create an array of even numbers
even_numbers = np.arange(10, 70, 2)
print("Even numbers:", even_numbers)

# b. Perform at least three element-wise mathematical operations:

# Ensure the arrays have the same size
if len(odd_numbers) > len(even_numbers):
    odd_numbers = odd_numbers[:-1]
elif len(odd_numbers) < len(even_numbers):
    even_numbers = even_numbers[:-1]

# Element-wise addition
addition_result = odd_numbers + even_numbers
print("\nElement-wise addition result:\n", addition_result)

# Element-wise subtraction
subtraction_result = odd_numbers - even_numbers
print("\nElement-wise subtraction result:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = odd_numbers * even_numbers
print("\nElement-wise multiplication result:\n", multiplication_result)

# c. Sort a given array by row and column:

array = np.array([[5.54, 3.38, 7.99],
                 [3.54, 4.38, 6.99],
                 [1.54, 2.39, 9.29]])

# Sort by rows
row_sorted_array = np.sort(array, axis=1)
print("\nArray sorted by rows:\n", row_sorted_array)

# Sort by columns
column_sorted_array = np.sort(array, axis=0)
print("\nArray sorted by columns:\n", column_sorted_array)


Odd numbers: [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
Even numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68]

Element-wise addition result:
 [ 21  25  29  33  37  41  45  49  53  57  61  65  69  73  77  81  85  89
  93  97 101 105 109 113 117 121 125 129 133 137]

Element-wise subtraction result:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Element-wise multiplication result:
 [ 110  156  210  272  342  420  506  600  702  812  930 1056 1190 1332
 1482 1640 1806 1980 2162 2352 2550 2756 2970 3192 3422 3660 3906 4160
 4422 4692]

Array sorted by rows:
 [[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Array sorted by columns:
 [[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


#Q5

In [ ]:
import numpy as np

# Declare the given array
Array = np.array([[4, 2, np.nan, 1],
                 [11, 12, 14, 9],
                 [5, np.nan, 1, np.nan]])

print("Original Array:\n", Array)

# Check for missing values (nan)
missing_data = np.isnan(Array)
print("\nMissing Data (Boolean output):\n", missing_data)


Original Array:
 [[ 4.  2. nan  1.]
 [11. 12. 14.  9.]
 [ 5. nan  1. nan]]

Missing Data (Boolean output):
 [[False False  True False]
 [False False False False]
 [False  True False  True]]
